apiVersion: v1
kind: Service
metadata:
  name: frontend-dsi-app
  labels:
    run: frontend-dsi-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: frontend-dsi-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-dsi-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: frontend-dsi-app
    spec:
      containers:
      - name: frontend-dsi-app
        image: iortizf/frontend-dsi:1.0
        ports:
        - containerPort: 80
        - containerPort: 443  
